
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /sse
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    encoding: utf-8
    # 禁用缓存
    cache: false
#    mode: HTML5
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: mysql
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    servlet:
      load-on-startup: 100
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.decision
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/*Dao.xml


# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: 
  # 匹配链接
  urlPatterns: 
